---
# This playbook deploys a simple standalone setup.

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    username: liquid
    password: $1$liquid$2ak0W/7tfA.HgMLh3KPRq/

  tasks:
  - name: "yum | install ansible vim git"
    yum: name={{ item }} state=latest
    with_items:
      - ansible
      - git
      - vim

  - name: "user | create {{ username }}"
    user:
      name: "{{ username }}"
      comment: "{{ username }}"
      uid: 2000
      group: adm
      password: "{{ password }}"
