---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: liquid
  become: yes
  become_method: sudo
  # remote_user: root


  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
